export const depositMoneyConstants = {
    DEPOSIT_MONEY_REQUEST: 'DEPOSIT_MONEY_REQUEST',
    DEPOSIT_MONEY_SUCCESS: 'DEPOSIT_MONEY_SUCCESS',
    DEPOSIT_MONEY_FAILURE: 'DEPOSIT_MONEY_FAILURE',

    VERIFY_PIN_REQUEST: 'VERIFY_PIN_REQUEST',
    VERIFY_PIN_SUCCESS: 'VERIFY_PIN_SUCCESS',
    VERIFY_PIN_FAILURE: 'VERIFY_PIN_FAILURE',

    VERIFY_CARD_REQUEST: 'VERIFY_CARD_REQUEST',
    VERIFY_CARD_SUCCESS: 'VERIFY_CARD_SUCCESS',
    VERIFY_CARD_FAILURE: 'VERIFY_CARD_FAILURE',

};
